# Generated by Django 4.0.4 on 2022-05-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='join2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=102)),
                ('Experience', models.IntegerField()),
                ('Message', models.TextField(max_length=400)),
                ('Cv', models.FileField(upload_to='')),
                ('Remote', models.CharField(max_length=100)),
                ('Re', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='Email',
        ),
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=122),
            preserve_default=False,
        ),
    ]
