# Generated by Django 4.0.4 on 2022-05-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_join2_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join2',
            name='Cv',
            field=models.CharField(max_length=250),
        ),
    ]
